version: '3'
services:
  my-app:
    image: uadeel421/nana-project:latest
    container_name: my-app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - .env
   
  mongodb:
    image: mongo:8.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_PWD}
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    
  mongo-express:
    image: mongo-express      
    container_name: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${USER_PWD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongodb
    env_file:
      - .env
    
volumes:
  mongo-data:
    driver: local