apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-url
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password      
        
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
      app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
