name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: app  # 👈 This ensures npm ci runs inside the "app" folder

    - name: Build the Application
      run: npm run build --if-present
      working-directory: app  # 👈 Run build inside "app"

    - name: Run Tests
      run: npm test
      working-directory: app  # 👈 Run tests inside "app"
