name: Node.js CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Debug Docker Credentials
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Password Length: ${#DOCKER_PASSWORD}"

      - name: Build the Docker Image
        run: docker build -t uadeel/cdrepo:${{ github.sha }} .
  
      - name: Push Docker Image to Docker Hub
        run: docker push uadeel/cdrepo:${{ github.sha }}
